version: '3'
services:
  elastichost:
    image: elasticsearch:7.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.tipe=single-node
  kibana:
    image: kibana:7.8.0
    ports:
      - "5601:5601"