version: '3.0'
services:
  elasticsearch:
    image: elasticsearch:8.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    networks:
      - stack
  kibana:
    platform: linux/amd64
    image: kibana:8.3.2
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    environment:
      - xpack.security.enabled=false      
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH.SSL.VERIFIVATIONMODE=none
    networks:
      - stack
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  app:
    build: ./
    depends_on:
      - fluentdhost
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentdhost
        fluentd-async: 'true'
    networks:
      - stack    
  fluentdhost:
    build: ./fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    networks:
      - stack
networks:
  stack:
 #docker build -t node-logger-app . 
#docker run --name logger-app --network js-logging-fluentd_stack --rm node-logger-app